@echo off
echo Cleaning Unreal Engine project...

echo Deleting Binaries folder...
rmdir /s /q "C:\Users\Bartek\Documents\Unreal Projects\VrPiano554\Binaries"

echo Deleting .vs folder...
rmdir /s /q "C:\Users\Bartek\Documents\Unreal Projects\VrPiano554\.vs"

echo Deleting Intermediate folder...
rmdir /s /q "C:\Users\Bartek\Documents\Unreal Projects\VrPiano554\Intermediate"

echo Deleting Saved folder...
rmdir /s /q "C:\Users\Bartek\Documents\Unreal Projects\VrPiano554\Saved"

echo Deleting VrPiano554.sln file...
del /f /q "C:\Users\Bartek\Documents\Unreal Projects\VrPiano554\VrPiano554.sln"

echo Deleting .vsconfig file...
del /f /q "C:\Users\Bartek\Documents\Unreal Projects\VrPiano554\.vsconfig"

echo Cleaning complete.